apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-node
  name: hello-node
  selfLink: /api/v1/namespaces/default/services/hello-node
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32614
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
